### PR TITLE
Bump some deps versions to be able to build with openssl v0.10

### LINKED ISSUE #2: Unable to build docker container
First, I think libssl-dev is missing during the build. Moved it like in this patch:

```patch
diff --git Dockerfile Dockerfile
index 5845a11..08f1171 100644
--- Dockerfile
+++ Dockerfile
@@ -12,6 +12,9 @@ RUN rustc --version && \
     rustup --version && \
     cargo --version
 
+RUN apt-get update
+RUN apt-get install -y libssl-dev default-libmysqlclient-dev
+
 RUN cargo clean && cargo build --release
 RUN strip ./target/release/raider
 
@@ -22,9 +25,6 @@ WORKDIR /usr/src/raider
 COPY ./res/assets/ ./res/assets/
 COPY --from=build /app/target/release/raider /usr/local/bin/raider
 
-RUN apt-get update
-RUN apt-get install -y libssl-dev default-libmysqlclient-dev
-
 CMD [ "raider", "-c", "/etc/raider.cfg" ]
 
 EXPOSE 8080
```

But even then, I suspect it fails because the installed libssl version is newer than what's expected:

```
$ docker build -t raider .
...
default-libmysqlclient-dev is already the newest version (1.0.5).
libssl-dev is already the newest version (1.1.1d-0+deb10u3).
...
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/app/target/release/build/openssl-e0c9d0620fbd0538/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
```

Attached full [build.log](https://github.com/valeriansaliou/raider/files/4862478/build.log).

I'd prefer to actually not use a container but my libssl-dev version on host is newer, too. So, same result. 
I'll try and see if I can bump deps versions and make them use newer libssl.

### PR DESCRIPTION
**Pull request by x1ddos**
Both build in docker and on host fail with a fairly recent libssl
like 3.0.

This commit selectively bumps up some deps like native-tls and reqwest
to get the deps tree result only in openssl 0.10.x. This of course
lead to some package APIs changes and required a bit modifications
to the source code in this project.

Unfortunately, rocket still requires nightly.

Built with rustc 1.46.0-nightly.

Closes https://github.com/valeriansaliou/raider/issues/2

### CODE REVIEW

**Comment by x1ddos** [comment]
Also switched Travis-CI to `nightly-2020-06-30`. Let's see if that works.

**Comment by x1ddos** [comment]
Sorry, config.cfg changes got in by mistake. Reverted.
PTAL

**Comment by x1ddos** [comment]
I swear this is the last time. Simplified `lettre::SmtpTransport` usage, almost exactly the way it was before this PR.
PTAL.

**Comment by valeriansaliou** [comment]
Thanks for your works, looks good to me!

**Pull request merged**
